### ISSUE TITLE
Focus not released on demo page

### ISSUE THREAD

**Issue by inca** [lucthev/compose#78]
Hi,

When I click on the editable title at the [demo page](http://thevenard.me/compose/) I am unable to switch back to edit the main page content.

P.S. I've been scouting web in a quest for the contenteditable-based editor for the last three days. The Compose seems like the best of them (considering philosophy, modularity, npm/browserify-friendliness, plugin-based architecture, etc.). Congratulations on a great product! Really looking forward for the release :)

**Comment by lucthev** [comment]
Hello, and thanks for the bug report.

The demo paged is based on a *really* [old version][old] of Compose; at the time, it was essentially a rehashing of the Guardian’s [Scribe][scribe], and it was buggy and hard to reason about. The new architecture should (hopefully) eliminate these problems; once it’s ready, I’ll update the demo. In the meantime, I’ve removed the link from the repo.

Thanks for the kind words! If you’re feeling adventurous, feel free to contribute — I’d be happy to help you get started.

[old]: https://github.com/lucthev/compose/tree/55cc13e8c495a797895033e888f5b49719fcfcc4
[scribe]: https://github.com/guardian/scribe

**Comment by inca** [comment]
Is there any recommended reading about the new architecture (especially what `view.js` plugin does)?

**Comment by lucthev** [comment]
Compose is loosely based off of Medium’s editor, the basics of which are explained [here][medium]. The `view` plugin, along with the `delta` plugin, is how you interact with the editor. I’ll create some documentation once the API stabilises; in the meantime, you can check out the [block formatting plugin][block] for an example of how it works.

[medium]: https://medium.com/medium-eng/why-contenteditable-is-terrible-122d8a40e480
[block]: https://github.com/lucthev/compose-formatblock

**Comment by inca** [comment]
Yes, I've read this article on Medium, it (along with some thoughts of my own) was the exact reason I liked Compose. Awesome job!
